[FPADF] Announcement
FreeCAD/FPA pull request #25
Opened 2022-10-28 13:51 UTC by WandererFan

An announcement of FPADF and description of process.  re issue #24

2022-10-28 14:19 UTC, sliptonic requested changes
Great start!  This needs to happen.

2022-10-28 14:19 UTC, sliptonic commented on FPADF_Announcement.md
> +Initially, grants from the FPADF will be capped at US$1000 and grants will be awarded only for work on the FreeCAD code base.
```suggestion
Grants are capped at US$1000 and will be awarded only for work on the FreeCAD code base.
```

2022-10-28 14:19 UTC, sliptonic commented on FPADF_Announcement.md
> +Initially, grants from the FPADF will be capped at US$1000 and grants will be awarded only for work on the FreeCAD code base.
Avoid casting the current announcment as suboptimal or inferior to a future goal.

2022-10-28 14:19 UTC, sliptonic commented on FPADF_Announcement.md
> +It is expected that grants will eventually be made available to contributors working on documentation, packaging, and other aspects of FreeCAD.
```suggestion

```

2022-10-28 14:19 UTC, sliptonic commented on FPADF_Announcement.md
> +Any contributor who wishes to be considered for a grant must submit a proposal in writing to the FPA. The contributor must state clearly how much money is requested and what the contributor intends t
```suggestion
Any contributor who wishes to be considered for a grant should submit a proposal in writing to the FPA. The proposal should state clearly how much money is requested and what the contributor intends to create/improve/fix. An estimated timeline with major milestones should be included along with clear completion criteria.
```

2022-10-28 14:19 UTC, sliptonic commented on FPADF_Announcement.md
> +
```suggestion
The FreeCAD Project Association would like to expand the number and type of grants given.  Donations made to the FPA and designated DEVELOPMENT FUND will be used for this purpose. 
```

2022-10-28 23:53 UTC, chennes commented
Do we say someplace else how exactly one "submits a proposal to the FPA"?

2022-10-29 13:11 UTC, WandererFan commented
> Do we say someplace else how exactly one "submits a proposal to the FPA"?

Just the bit about "forward to any member of the FPA".   We don't have an FPA email?  We could add "via private message on the FreeCAD forum".

2022-10-30 19:11 UTC, sliptonic approved these changes

2022-11-02 13:33 UTC, sliptonic commented
> What next? Merge this PR. Post in FC Forum. Post in blog.
> 
> Do we need wider approval first?

Let's roll with it.  It looks good to me and has had sufficient time for feedback.  It makes a great blog post.  A forum post and twitter post linking to the blog post would be great.

2022-11-02 13:33 UTC, merged